package com.otto.tasks_crud.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;

@Entity // Annotates the class as an entity to be managed by JPA
@Table(name = "tasks") // Specifies the table name in the database to map to this entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS) // Defines the inheritance strategy for subclasses
public class MainTask extends Task {

    public MainTask() {
        super(null, null, null, null);
    }

    public MainTask(String id, String title, String description, java.util.Date startDate, java.util.Date endDate,
            List<Subtask> subtasks) {
        super(title, description, startDate, endDate);
        this.id = Long.parseLong(id);
        this.subtasks = subtasks;
    }

    @Id // Annotates the id property as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be auto-generated by the
                                                        // database
    private Long id;

    @OneToMany(mappedBy = "task") // Specifies a one-to-many relationship between MainTask and Subtask
    @JsonManagedReference // Indicates that the subtasks list is managed by the MainTask entity
    private List<Subtask> subtasks;

    ///
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Subtask> getSubtasks() {
        return subtasks;
    }

    public void setSubtasks(List<Subtask> subtasks) {
        this.subtasks = subtasks;
    }
}
